services:
  web:
    image: web:latest
    build:
      context: .
      dockerfile: web/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/squash
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_KEY=minioadmin
      - MINIO_SECRET=minioadmin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - minio
      - redis
      - worker

  worker:
    image: worker:latest
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/squash
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_KEY=minioadmin
      - MINIO_SECRET=minioadmin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - minio
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: squash
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/origin;
      /usr/bin/mc mb myminio/compressed;
      exit 0;
      "

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  minio_data:
  redis_data:
